services:
    rates123:
        build:
            context: ./docker/prod
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
        volumes:
            - '.:/app'
        networks:
            - medeirostec-network
        depends_on:
            - redis
    redis:
        image: 'redis:alpine'
        volumes:
            - 'rates123-redis:/data'
        networks:
            - medeirostec-network
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

networks:
  medeirostec-network:
      external: true
      name: medeirostec-network
      driver: bridge

volumes:
    rates123-redis:
        driver: local
